# Generated by Django 3.2.10 on 2021-12-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'hour']},
        ),
    ]
